AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/*'

plugins:
  - rubocop-rails
  - rubocop-performance

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
