AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

plugins:
  - rubocop-rails
  - rubocop-performance

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25
