AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-graphql

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/IndexedLet:
  Enabled: false

GraphQL/ObjectDescription:
  Exclude:
    - 'spec/**/*'
    - 'app/graphql/*/*_schema.rb'
    - 'app/graphql/*/types/base_*.rb'
    - 'app/graphql/*/types/mutation_type.rb'
    - 'app/graphql/*/types/query_type.rb'
    - 'app/graphql/*/mutations/base_*.rb'
    - 'app/graphql/*/mutations/*/*.rb'
    - 'app/graphql/*/helpers/*.rb'
