default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= Integer(ENV.fetch('DATABASE_POOL', 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch('DATABASE_REAPING_FREQUENCY', 60)) %>
  timeout: <%= Integer(ENV.fetch('DATABASE_TIMEOUT', 5000)) %>

development:
  <<: *default
  database: base_app_development

test:
  <<: *default
  database: base_app_test

# TODO: cache/queue/cable custom configuration
production:
  primary: &primary_production
    <<: *default
  cable:
    <<: *primary_production
    database: base_app_production_cable
    migrations_paths: db/cable_migrate
