default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Integer(ENV.fetch('DATABASE_POOL', 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch('DATABASE_REAPING_FREQUENCY', 10)) %>
  timeout: 5000

development: &development
  <<: *default
  database: base_app_development
  username: base_app
  password:
  # host: localhost
  # port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *development
  database: base_app_test
