---
:verbose: false
:timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 25) %>
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues: <%= ENV.fetch('SIDEKIQ_QUEUES', 'default,high,low,mailers,turbo_streams').split(',').map(&:strip).to_s %>
