---
:verbose: false
:timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 25) %>
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues: <%= ENV.fetch('SIDEKIQ_QUEUES', 'default,high,mailers').split(',').map(&:strip).to_s %>
