# https://github.com/mperham/sidekiq/blob/master/examples/config.yml
# Sidekiq picks up this file automatically.
# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
# Options here can still be overridden by cmd line args.
---
:verbose: false
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 30) %>

:queues: <%= ENV.fetch('SIDEKIQ_QUEUES', 'default,high,mailers').split(',').map(&:strip).to_s %>
