name: RSpec

on:
  push:
    branches:
      - main
  pull_request:

env:
  RACK_ENV: test
  RAILS_ENV: test
  SECRET_KEY_BASE: 368ff1a04146545057690d897547969a
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432
  REDIS_CACHE_URL: redis://localhost:6379/0
  AWS_EC2_METADATA_DISABLED: true
  SIDEKIQ_REDIS_URL: redis://localhost:6379/0
  ANYCABLE_BINARY: https://github.com/anycable/anycable/releases/download/v1.6.1/anycable-go-linux-amd64
  ANYCABLE_RPC_POOL_SIZE: 5
  ANYCABLE_REDIS_URL: redis://localhost:6379/0
  ANYCABLE_SECRET: 6bd541cde3eaef4346468ffa2271fa00
  ANYCABLE_WEBSOCKET_URL: ws://localhost:8123/cable

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: base_app_test
        ports:
          - 5432:5432
      redis:
        image: redis:8-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libvips-tools

      - name: Install AnyCable
        run: |
          curl -L -o /usr/local/bin/anycable-go ${{ env.ANYCABLE_BINARY }}
          chmod +x /usr/local/bin/anycable-go

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install packages
        run: npm ci

      - name: Run RSpec
        run: bundle exec rspec

      - name: Upload capybara screenshots
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: capybara-screenshots
          path: tmp/capybara
          if-no-files-found: ignore
